// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.2.16 by WSRD Tencent.
// Generated from `SLGMapConfigProto.jce'
// **********************************************************************

using System;
using System.Collections.Generic;

namespace SLGMapConfig
{
    public sealed class MapLayerConfigClient : Wup.Jce.JceStruct
    {
        public List<List<SLGMapConfig.MapSlotInfoClient>> vectSlot {get; set;} 

        public int iMaxX = 0;

        public int iMAxY = 0;

        public override void WriteTo(Wup.Jce.JceOutputStream _os)
        {
            _os.Write(vectSlot, 0);
            _os.Write(iMaxX, 1);
            _os.Write(iMAxY, 2);
        }

        public override void ReadFrom(Wup.Jce.JceInputStream _is)
        {
            vectSlot = (List<List<SLGMapConfig.MapSlotInfoClient>>) _is.Read(vectSlot, 0, false);

            iMaxX = (int) _is.Read(iMaxX, 1, false);

            iMAxY = (int) _is.Read(iMAxY, 2, false);

        }

        public override void Display(System.Text.StringBuilder _os, int _level)
        {
            Wup.Jce.JceDisplayer _ds = new Wup.Jce.JceDisplayer(_os, _level);
            _ds.Display(vectSlot, "vectSlot");
            _ds.Display(iMaxX, "iMaxX");
            _ds.Display(iMAxY, "iMAxY");
        }

    }
}

