// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.2.16 by WSRD Tencent.
// Generated from `SLGMapConfigProto.jce'
// **********************************************************************

using System;
using System.Collections.Generic;

namespace SLGMapConfig
{

    public sealed class MapSlotInfoServer : Wup.Jce.JceStruct
    {
        public int iX = 0;

        public int iY = 0;

        public List<int> vectLogicLayers {get; set;} 

        public int iTerrainLayer = 0;

        public int iTerrainObject = 0;

        public int iTerrainType = 0;

        public override void WriteTo(Wup.Jce.JceOutputStream _os)
        {
            _os.Write(iX, 0);
            _os.Write(iY, 1);
            _os.Write(vectLogicLayers, 2);
            _os.Write(iTerrainLayer, 3);
            _os.Write(iTerrainObject, 4);
            _os.Write(iTerrainType, 5);
        }

        public override void ReadFrom(Wup.Jce.JceInputStream _is)
        {
            iX = (int) _is.Read(iX, 0, false);

            iY = (int) _is.Read(iY, 1, false);

            vectLogicLayers = (List<int>) _is.Read(vectLogicLayers, 2, false);

            iTerrainLayer = (int) _is.Read(iTerrainLayer, 3, false);

            iTerrainObject = (int) _is.Read(iTerrainObject, 4, false);

            iTerrainType = (int) _is.Read(iTerrainType, 5, false);

        }

        public override void Display(System.Text.StringBuilder _os, int _level)
        {
            Wup.Jce.JceDisplayer _ds = new Wup.Jce.JceDisplayer(_os, _level);
            _ds.Display(iX, "iX");
            _ds.Display(iY, "iY");
            _ds.Display(vectLogicLayers, "vectLogicLayers");
            _ds.Display(iTerrainLayer, "iTerrainLayer");
            _ds.Display(iTerrainObject, "iTerrainObject");
            _ds.Display(iTerrainType, "iTerrainType");
        }

    }
}

