// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.2.16 by WSRD Tencent.
// Generated from `SLGMapConfigProto.jce'
// **********************************************************************

using System;
namespace SLGMapConfig
{
    public enum EMapSlotLogicType
    {
        EMapSlotLogicType_Invalid = 0,
    }
}
